import React from "react";
import styles from "./eeg.module.css";
import eegSignal from "../../../assets/eegSignal.png"; // same way as ECG & EMG

export const Eeg = () => {
  return (
    <div className={styles.ecgContainer}>
      <p className={styles.paragraph}>
        <b>Electroencephalogram (EEG)</b> is the recorded representation of the
        bioelectric potential generated by the neuronal activity of the brain.
      </p>

      <p className={styles.paragraph}>
        <b>Origin:</b> Generated by the electrical activity of neurons in the
        brain, resulting mainly from postsynaptic potentials of large groups of
        cortical cells.
      </p>

      <h3 className={styles.subHeading}>Signal Characteristics</h3>
      <ul className={styles.list}>
        <li>Amplitude: Approximately 10 – 100 μV (peak)</li>
        <li>Frequency content: From DC up to ~100 Hz</li>
        <li>
          Electrodes: Measured with surface electrodes on the scalp and with
          needle electrodes just beneath the surface or driven into specific
          locations within the brain.
        </li>
      </ul>

      <h3 className={styles.subHeading}>Clinical Significance</h3>
      <p className={styles.paragraph}>
        Helps detect and diagnose neurological disorders such as epilepsy,
        enables spectral analysis of brain activity and measurement of evoked
        potentials, and plays a key role in monitoring brain states like sleep,
        consciousness, and anesthesia.
      </p>
      {/* <ul className={styles.list}>
        <li>Helps detect and diagnose neurological disorders such as epilepsy</li>
        <li>
          Useful for spectral analysis of brain activity and for measuring evoked
          potentials in response to stimuli
        </li>
        <li>
          Plays a key role in monitoring brain states like sleep, consciousness,
          and anesthesia
        </li>
      </ul> */}

      <h3 className={styles.subHeading}>
        Typical EEG Waveforms and Frequency Bands
      </h3>
      <p className={styles.paragraph}>
        EEG signals vary depending on electrode placement and brain activity.
        They are categorized into frequency bands that correlate with mental
        states:
      </p>

      <ul className={styles.list}>
        <li>
          <b>Delta (below 3 Hz):</b> Prominent in deep sleep
        </li>
        <li>
          <b>Theta (3–8 Hz):</b> Associated with light sleep and drowsiness
        </li>
        <li>
          <b>Alpha (8–13 Hz):</b> Seen when relaxed with eyes closed,
          representing synchronized brain activity
        </li>
        <li>
          <b>Beta (above 13 Hz):</b> Linked to alertness and active thinking,
          showing desynchronized patterns
        </li>
      </ul>

      <img src={eegSignal} alt="EEG Signal" className={styles.ecgImage} />
    </div>
  );
};
