import React from "react";
import styles from "./ecg.module.css";
import ecgImage from "../../../assets/ecgSignal.png";

export const Ecg = () => {
  return (
    <div className={styles.ecgContainer}>
      <p className={styles.paragraph}>
        <b>Electrocardiogram (ECG)</b> is the recording of the heart’s
        electrical activity, obtained by measuring the biopotentials generated
        during depolarization and repolarization of the cardiac muscles.
      </p>

      <p className={styles.paragraph}>
        <b>Origin:</b> Generated by the biopotentials of the heart muscles
        during depolarization and repolarization.
      </p>

      <h3 className={styles.subHeading}>Signal Characteristics</h3>
      <ul className={styles.list}>
        <li>Amplitude: Approximately 0.1 – 4 mV</li>
        <li>Frequency content: From DC up to ~100 Hz</li>
        <li>
          Electrodes: Measured using surface electrodes placed at specific
          points on the body
        </li>
      </ul>

      <h3 className={styles.subHeading}>Clinical Significance</h3>
      <p className={styles.paragraph}>
        Used to assess heart rate and rhythm, detect cardiac abnormalities such
        as arrhythmias and conduction defects, and provide a valuable timing
        reference in cardiovascular measurements.
      </p>
      {/* <ul className={styles.list}>
        <li>Used to assess heart rate and rhythm</li>
        <li>
          Helps detect cardiac abnormalities such as arrhythmias and conduction
          defects
        </li>
        <li>
          Provides a valuable timing reference in cardiovascular measurements
        </li>
      </ul> */}

      <h3 className={styles.subHeading}>Typical ECG Waveform</h3>
      <p className={styles.paragraph}>
        The diagram below shows the principal components of a standard ECG
        signal:
      </p>
      <div className={styles.ecgImageContainer}>
        <img src={ecgImage} alt="ECG Signal" className={styles.ecgImage} />
        <ul className={styles.list}>
          <li>
            <b>P wave:</b> Atrial depolarization
          </li>
          <li>
            <b>QRS complex:</b> Ventricular depolarization
          </li>
          <li>
            <b>T wave:</b> Ventricular repolarization
          </li>
        </ul>
      </div>

      <p className={styles.paragraph}>
        Various intervals, such as the PR interval and QT interval, correspond
        to different phases of the cardiac cycle. Each feature can be analyzed
        to assess heart function and detect abnormalities.
      </p>
    </div>
  );
};
