import React from "react";
import styles from "./emg.module.css";
import emgSignal from "../../../assets/emgSignal.png"; // same style as ecg image

export const Emg = () => {
  return (
    <div className={styles.ecgContainer}>
      <p className={styles.paragraph}>
        <b>Electromyogram (EMG)</b> is the recording of bioelectric potentials generated by skeletal muscles during contraction and relaxation.
      </p>

      <p className={styles.paragraph}>
        <b>Origin:</b> Generated by the depolarization and repolarization of
        muscle fibers, primarily reflecting the summed action potentials of
        motor units in skeletal muscle.
      </p>

      <h3 className={styles.subHeading}>Signal Characteristics</h3>
      <ul className={styles.list}>
        <li>Amplitude: Approximately 50 μV to 1 mV</li>
        <li>Frequency content: From about 10 Hz up to 3 kHz</li>
        <li>
          Electrodes: Measured with surface electrodes on the skin or needle electrodes
            penetrating the muscles fibre.

        </li>
      </ul>

      <h3 className={styles.subHeading}>Clinical Significance</h3>
      <p className={styles.paragraph}>
        Indicates muscle contraction intensity and timing, used to study muscle
        fatigue and neuromuscular function.
      </p>

      <h3 className={styles.subHeading}>Typical EMG Waveform</h3>
      <p className={styles.paragraph}>
        The EMG signal is a complex, noise-like pattern representing the
        instantaneous sum of action potentials from multiple muscle fibers. When
        the muscle is at rest (baseline), the signal is minimal. During
        contraction, the waveform amplitude increases, producing an interference
        pattern. The energy and shape of the EMG waveform depend on muscle
        activity level and electrode placement.
      </p>

      <img src={emgSignal} alt="EMG Signal" className={styles.ecgImage} />
    </div>
  );
};
